---
- name: Kafka Provisioning
  hosts: all
  remote_user: root
  gather_facts: false
  tags: base_install
  tasks:
    - name: apt-get update and upgrade
      apt:
        update_cache: yes
        upgrade: full
        force_apt_get: yes
    - name: install java and docker
      apt:
        name: openjdk-11-jdk, jq, docker, docker-compose, python3, python3-pip
        state: latest
        force_apt_get: yes
    - name: Installing Python Modules
      pip:
        name:
          - ruamel.yaml, yq, psutil
    - name: Adding user ubuntu to Docker group
      ansible.builtin.user:
        name: ubuntu
        append: true
        groups: docker
    - name: Cloning IoT GitHub repo
      git:
        repo: 'https://github.com/berthayes/iot.git'
        dest: /home/ubuntu/iot
    - name: Copying hosts.yml
      copy:
        src: hosts.yml
        dest: /home/ubuntu/iot/hosts.yml
    - name: Copying yak_shaving.conf
      copy:
        src: yak_shaving.conf
        dest: /home/ubuntu/iot/yak_shaving.conf
###
- name: Configure Confluent REST Proxy
  hosts: rest_proxy
  remote_user: root
  gather_facts: false
  tags: kafka_rest
  tasks:
    - name: Set the hostname to rest-proxy
      ansible.builtin.hostname:
        name: rest-proxy
    - name: Copying ccloud-kafka-rest.properties
      copy:
        src: ccloud-kafka-rest.properties
        dest: /home/ubuntu/iot/ccloud-kafka-rest.properties
    - name: Creating docker-compose.yml file
      command: /usr/bin/python3 /home/ubuntu/iot/scripts/create_rest_proxy_docker_compose.py
    - name: Starting Docker
      shell:
        cmd: docker-compose -f rest-docker-compose.yml up -d
###
- name: Configure MQTT Source Kafka Connect node
  hosts: kafka_connect_mqtt
  remote_user: root
  gather_facts: false
  tags: kafka_connect
  tasks:
    - name: Set the hostname to mqtt-connect
      ansible.builtin.hostname:
        name: mqtt-connect
    - name: Copying my-connect-distributed.properties
      copy:
        src: my-connect-distributed.properties
        dest: /home/ubuntu/iot/my-connect-distributed.properties
    - name: Creating docker-compose.yml file
      command: /usr/bin/python3 /home/ubuntu/iot/scripts/create_mqtt_connect_docker_compose_dot_yaml.py
    - name: Starting Docker
      shell:
        cmd: docker-compose -f docker-compose.yml up -d
    - name: Wait 60 seconds for connect to start up
      pause:
        seconds: 60
    - name: Create config file for mqtt source connector
      command: /usr/bin/python3 /home/ubuntu/iot/create_mqtt_config.py
    - name: Start MQTT Source Connector
      command: /bin/sh /home/ubuntu/iot/start_mqtt_connect.sh
###
- name: Configure the Prometheus Sink Connector
  hosts: kafka_connect_prometheus
  remote_user: root
  gather_facts: false
  tags: kafka_connect_prometheus
  tasks:
    - name: Set the hostname to prometheus-connect
      ansible.builtin.hostname:
        name: prometheus-connect
    - name: Copying my-connect-distributed.properties to prometheus connect
      copy:
        src: my-connect-distributed.properties
        dest: /home/ubuntu/iot/my-connect-distributed.properties
    - name: Creating docker-compose.yml file
      command: /usr/bin/python3 /home/ubuntu/iot/scripts/create_prometheus_connect_docker_compose_dot_yaml.py
    - name: Starting Docker
      shell:
        cmd: docker-compose -f docker-compose.yml up -d
    - name: Create config file for Prometheus Sink Connector
      command: /usr/bin/python3 /home/ubuntu/iot/create_prometheus_sink_config.py
    - name: Wait 60 seconds for connector to start up
      pause:
        seconds: 60
    - name: Start Prometheus Sink Connector
      command: /bin/sh /home/ubuntu/iot/start_prometheus_sink_connect.sh
###
- name: Configure the Prometheus Server
  hosts: prometheus_server
  remote_user: root
  gather_facts: false
  tags: prometheus_server
  tasks:
    - name: Set the hostname to prometheus-server
      ansible.builtin.hostname:
        name: prometheus-server
    - name: Creating prometheus.yml
      command: /usr/bin/python3 /home/ubuntu/iot/scripts/make_prometheus_server_config.py
    - name: installing prometheus
      apt:
        name: prometheus
        state: latest
        force_apt_get: yes
    - name: moving Prometheus.yml config file
      command: mv /home/ubuntu/prometheus.yml /etc/prometheus/prometheus.yml
    - name: starting prometheus server
      ansible.builtin.command:
        cmd: /usr/bin/prometheus --config.file="/home/ubuntu/prometheus.yml"
###
- name: Configuring the Postgres server
  hosts: postgres
  remote_user: root
  gather_facts: false
  tags: postgres_server
  tasks:
    - name: Copying postgres-docker-compose.yml
      copy:
        src: postgres-docker-compose.yml
        dest: /home/ubuntu/postgres-docker-compose.yml
    - name: Starting Docker
      shell:
        cmd: docker-compose -f postgres-docker-compose.yml up -d


